spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.data.redis.autoconfigure.DataRedisRepositoriesAutoConfiguration
  application:
    name: nexus-gateway

management:
  endpoint:
    gateway:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: health,gateway

server:
  port: 8080
