spring:
  application:
    name: nexus-gateway

management:
  endpoint:
    gateway:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: health,gateway

server:
  port: 8080